# Generated by Django 5.2 on 2025-04-09 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('photo', models.ImageField(upload_to='tutors/')),
                ('admission_criteria', models.TextField(blank=True, null=True)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50)),
                ('is_registered', models.BooleanField(default=False)),
                ('hire_date', models.DateTimeField(auto_now_add=True)),
                ('login_id', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
