# Generated by Django 5.2 on 2025-04-10 03:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='admission_criteria',
            field=models.TextField(validators=[django.core.validators.MaxLengthValidator(5000)]),
        ),
    ]
