# Generated by Django 4.2.19 on 2025-04-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutors', '0002_alter_tutor_hire_date_alter_tutor_name'),
        ('courses', '0002_alter_course_admission_criteria'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='title',
            field=models.CharField(default='Untitled Course', max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_code',
            field=models.CharField(choices=[('AB-0001', 'AB-0001'), ('AB-0002', 'AB-0002'), ('CA-0003', 'CA-0003'), ('CA-0004', 'CA-0004'), ('EA-0005', 'EA-0005')], max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(choices=[('A0001', 'English Conversation Elementary'), ('B0002', 'English Conversation Intermediate'), ('C0003', 'Mandarin Conversation Elementary'), ('D0004', 'Mandarin Conversation Intermediate'), ('E0005', 'Play Group')], max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutors.tutor'),
        ),
    ]
